# Generated by Django 3.1.7 on 2021-03-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210309_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catgory',
            new_name='category',
        ),
    ]
